### ISSUE TITLE
Support for additional CNI plug-ins 

### ISSUE THREAD

**Issue by sheetaljoshi** [Huawei-PaaS/CNI-Genie#36]
I am trying to use a bridge plugin but we do see message Only supported are (Romana, weave, canal, calico, flannel). Any ideas how difficult it is to support additional plugins(https://github.com/containernetworking/plugins/tree/master/plugins/main).

**Comment by kshafiee** [comment]
@sheetaljoshi 

PR #30 enables this feature. Feel free to pull the PR and use it. 
The idea is that it searches all of the .conf files under /etc/cni/net.d for the cni passed by the user in the Pod yaml. It then passes all of configs in the .conf file into the cni binary, e.g., calico, weave-net, etc.

The reason we did not merge this into master at this point is that it complicates CNI-Genie because
1. it fails if there is no .conf file for the cni passed by the user
2. CNI-Genie passes all of configs in the .conf file to the cni binary. So, if any if the configs in the .conf file is invalid, this will fail

Here is 2 examples pods that I just created using PR #30 
![image](https://user-images.githubusercontent.com/7294758/27937160-0027cb84-626a-11e7-9b7e-6f3745285fbb.png)
![image](https://user-images.githubusercontent.com/7294758/27937126-ba44a43e-6269-11e7-8e13-9dfcafc3f832.png)
![image](https://user-images.githubusercontent.com/7294758/27937150-e47eed54-6269-11e7-91eb-bd9ffb840446.png)

![image](https://user-images.githubusercontent.com/7294758/27937164-0ce0b958-626a-11e7-9cc8-f5521a685137.png)
![image](https://user-images.githubusercontent.com/7294758/27937176-1f02092a-626a-11e7-84a6-cfc482720723.png)
![image](https://user-images.githubusercontent.com/7294758/27937216-3f4b7de2-626a-11e7-9173-6147af3d4e66.png)

**Comment by kshafiee** [comment]
@sheetaljoshi the code is merged into master now. Any additional plugin can be supported now. All you need to do is to make sure you have the binary available in /opt/cni/bin and the .conf file available under /etc/cni/net.d
